Adjustment Preflight Check for Redhat based systems
tribe29/ansible-collection-tribe29.checkmk pull request #111
Opened 2022-08-24 00:18 UTC by mto79

## Pull request type

Please check the type of change your PR introduces:

- [x ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

1. The preflight check in the roles/server/tasks/main.yml checks for RHEL 7 and RHEL 8 with ansible_distribution.
    According to https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#ansible-facts-distribution it has toc check against RedHat 7 and RedHat 8.
 
2. Also the use of spaces is not nice if you are using without quotes.
 
3. The checks with for e.g. ansible_distribution are out dated.
    ![image](https://user-images.githubusercontent.com/3749354/186287655-ec72ab4e-962d-4b0c-9a8c-5e2290fd7337.png)
    See also: https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html 

## What is the new behavior?

- Check now on RedHat-7 and RedHat-8
- Use of '-' instead of space in the concat
- Use of ansible_facts['distribution'] instead of ansible_distribution etc.

## Other information
https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#ansible-facts-distribution
https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html

2022-08-24 01:09 UTC, mto79 commented
Should have make feature-branch for the second suggestion of including vars ...

2022-08-24 09:27 UTC, robin-tribe29 commented
@mto79 thanks for the fresh PR. Can you look at the checks and fix the findings?
I will take a closer look into this later.

2022-08-24 10:49 UTC, mto79 commented
> 

Thanks Robin, saw the trailing spaces indeed. Just fixed but will look closer tonight.

Also today i have been working on RedHat/Centos implementation of installation Checkmk server role further and i am in the phase of testing myself on DigitalOcean.)

Below a codefragment of what i am trying to test with RedHat en CentOS.
It is the implementation of powertools and Epel for the different distribution cases based on:

- https://docs.checkmk.com/latest/en/install_packages_redhat.html
- https://docs.fedoraproject.org/en-US/epel/#_el9

The current below code from (tasks/RedHat.yml) the role is only for CentOS 8 version i suppose. 
```
  ansible.builtin.shell: dnf config-manager --set-enabled powertools  # noqa command-instead-of-shell
  when: ansible_distribution_major_version == "8"
```

```
- name: "{{ ansible_facts.os_family|lower }} | install | enable powertools"
  ansible.builtin.command: "{{ item }}"
  loop:
    - "yum config-manager --enable rhel-7-server-optional-rpms"
    - "yum-config-manager --enable rhel-7-server-extras-rpms"
  when:
    - (ansible_facts.distribution == "CentOS" and ansible_facts.distribution_major_version == "7") or
      (ansible_facts.os_family == "RedHat" and ansible_facts.distribution_major_version == "7")

- name: "{{ ansible_facts.os_family|lower }} | install | Enable all repositories "
  community.general.rhsm_repository:
    name: "{{ item }}"
    state: enabled
  loop:
    - "rhel-7-server-optional-rpms"
    - "rhel-7-server-extras-rpms"
  when:
    - (ansible_facts.distribution == "CentOS" and ansible_facts.distribution_major_version == "7") or
      (ansible_facts.os_family == "RedHat" and ansible_facts.distribution_major_version == "7")

- name: "{{ ansible_facts.os_family|lower }} | install | enable powertools"
  ansible.builtin.command: dnf config-manager --set-enabled powertools
  when:
    - ansible_facts.distribution == "CentOS" and ansible_facts.distribution_major_version == "8"
  tags: ['checkmk-server-install']

- name: "{{ ansible_facts.os_family|lower }} | install | enable powertools"
  ansible.builtin.command: dnf config-manager --set-enabled crb
  when:
    - ansible_facts.distribution == "CentOS" and ansible_facts.distribution_major_version == "9"

- name: "{{ ansible_facts.os_family|lower }} | install | Enable all repositories "
  community.general.rhsm_repository:
    name: "codeready-builder-for-rhel-{{ ansible_facts.distribution_major_version }}-x86_64-rpms"
    state: enabled
  when:
    - ansible_facts.os_family == "RedHat" and ansible_facts.distribution_major_version in [ "8", "9" ])

- name: "{{ ansible_facts.os_family|lower }} | install | set epel-release from fedora download"
  block:
    - name: "{{ ansible_facts.os_family|lower }} | install | epel gpg key"
      ansible.builtin.rpm_key:
        key: "{{ checkmk_server_epel_gpg_key }}"
        state: present

    - name: "{{ ansible_facts.os_family|lower }} | install | epel-release"
      ansible.builtin.yum:
        name: "{{ checkmk_server_epel_url }}"
        state: present
      notify:
        - yum update cache
  when: checkmk_server_epel_dl_fedora|bool     

- name: "{{ ansible_facts.os_family|lower }} | install | epel-release "
  block:
    - name: "{{ ansible_facts.os_family|lower }} | install | epel-release"
      ansible.builtin.yum:
        name: "epel-release"
        state: present
      notify:
        - yum update cache
  when: not checkmk_server_epel_dl_fedora|bool    
```

If my findings are good i will open a PR if you are interested.

2022-08-24 13:44 UTC, diademiemi commented
How come some variables have an underscore prefixed to them, like `_checkmk_server_prerequisites`. Is this best practice when it comes to variables included from a role? (Which would be hard coded afaik and can not be overrules by passing variables to the run, correct me if I'm wrong)

2022-08-24 14:09 UTC, robin-tribe29 requested changes

2022-08-24 14:09 UTC, robin-tribe29 commented on roles/server/tasks/main.yml
> -  become: true
You cannot remove this. We need higher privileges here for package installations.

2022-08-24 14:09 UTC, robin-tribe29 commented on roles/server/tasks/main.yml
> +    url_password: "{{ checkmk_server_download_pass|default(omit) }}"
Jinja encourages spaces aroud pipes.

2022-08-24 14:09 UTC, robin-tribe29 commented on roles/server/tasks/main.yml
> +  loop: "{{ checkmk_server_prerequisites }}"
I am uncertain, if I understand how this loop works with the new variable structure.

2022-08-24 14:40 UTC, mto79 commented on roles/server/tasks/main.yml
> +    url_password: "{{ checkmk_server_download_pass|default(omit) }}"
Ah Will do!

2022-08-24 14:45 UTC, mto79 commented on roles/server/tasks/main.yml
> -  become: true
Well know what you mean at first glance. But if you look in vars/redhat.yml You see you do not need the precedence and the inclusion of var files on red hat version Numbers. 

The prerequisit packages variabele is adjusted special for that. (Array like)

2022-08-24 14:47 UTC, mto79 commented on roles/server/tasks/main.yml
> +  loop: "{{ checkmk_server_prerequisites }}"
It is somewhat different than the with_items. When running the server role i had to change it inline. Otherwise it saw an array

2022-08-24 14:48 UTC, diademiemi commented on roles/server/tasks/main.yml
> +  loop: "{{ checkmk_server_prerequisites }}"
Should be exactly the same, if yamllint and ansible-lint don't complain about this then I think it's better. The variable is a list anyway, so there's no functional difference, this just makes more sense.

2022-08-24 14:48 UTC, mto79 commented
Will make changes tonight.

2022-08-24 14:59 UTC, mto79 commented
> How come some variables have an underscore prefixed to them, like `_checkmk_server_prerequisites`? Is this best practice when it comes to variables included from a role? (Which would be hard coded afaik and can not be overrules by passing variables to the run, correct me if I'm wrong)

It is merely a temp variabele like locals in other languages , like in you can use with register for than debug massages.. it is merely style and to determine checkmk_server_prerequisities

2022-08-24 21:03 UTC, mto79 commented on roles/server/tasks/main.yml
> -  become: true
Will put this back

2022-08-24 21:40 UTC, mto79 commented
> > How come some variables have an underscore prefixed to them, like `_checkmk_server_prerequisites`? Is this best practice when it comes to variables included from a role? (Which would be hard coded afaik and can not be overrules by passing variables to the run, correct me if I'm wrong)
> 
> It is merely a temp variabele like locals in other languages , like in you can use with register for than debug massages.. it is merely style and to determine checkmk_server_prerequisities

@diademiemi found some elaboration:

Variable names can begin with an underscore. In many programming languages, variables that begin with an underscore are private. This is not true in Ansible. Variables that begin with an underscore are treated exactly the same as any other variable.

It iss frequently used as a dummy variable (a variable to receive a value from a function where the value is useless and never used).

But never use only the underscore  _ instead it must than be dummy.
https://docs.ansible.com/ansible/latest/dev_guide/testing/sanity/no-underscore-variable.html
(nice never knew that)

2022-08-25 06:36 UTC, robin-tribe29 commented on roles/server/tasks/main.yml
> +  loop: "{{ checkmk_server_prerequisites }}"
My uncertainty targets the logic behind the loop, not the syntax.

2022-08-25 06:42 UTC, robin-tribe29 commented
I never cared too much for variable names prefixes with underscores in Ansible. The geerlingguy does it too, I think, but I never saw the need. I would rather stick with the current naming convention, as long as there are no good technical reasons to change it.

2022-08-25 07:47 UTC, mto79 commented
> I never cared too much for variable names prefixes with underscores in Ansible. The geerlingguy does it too, I think, but I never saw the need. I would rather stick with the current naming convention, as long as there are no good technical reasons to change it.


Indeed big fan of geerlingguy :) It is as mentioned not technical .. merely style.  I will rename _checkmk_server_prerequisites to other variable.

2022-08-25 08:01 UTC, mto79 commented
I will take some time for ansible linting here local before committing!

2022-08-26 07:47 UTC, closed without merging