Feature host groups 1
tribe29/ansible-collection-tribe29.checkmk pull request #154
Opened 2022-09-19 09:24 UTC by msekania

Additional plugin that manages host groups. Created in close analogy with host.py and partly folders.py. In connection with rule module one can create a monitoring groups assigned to chosen subfolder.

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

-

## What is the new behavior?

- manage host groups in Checkmk (create/modify/delete)
- in connections with rule allows to monitor all hosts in the given subfolder

## Other information

For examle:

- name: "Create a single host group."
  tribe29.checkmk.host_group:
    server_url: "http://localhost/"
    site: "my_site"
    automation_user: "automation"
    automation_secret: "$SECRET"
    host_group_name: "my_host_group"
    title: "My Host Group"
    state: "present"

- name: "Check_MK: create/register rules, which assign all servers in the given folder to the corresponding host group"
  tribe29.checkmk.rule:
    server_url: "http://localhost/"
    site: "my_site"
    automation_user: "automation"
    automation_secret: "$SECRET"
    ruleset: "host_groups"
    rule:
        folder: "/My/Host_Groups"
        conditions: {
            "host_labels": [],
            "host_tags": [],
            "service_labels": []
        }
        properties: {
            "disabled": false,
        }
        value_raw: "'my_host_group'"
    state: "present"
  run_once: 'true'
  delegate_to: localhost

2022-09-19 09:26 UTC, msekania commented
simple module that manages host group, creates/deletes/modifies. created from host.py and partly folder.py

2022-09-22 11:29 UTC, msekania commented
Hi @lgetwan,

No, problem, I'll take a look at tests/integration/targets/host. I will get back to you if I will have any questions.

Meanwhile, I have almost finished bulk_host_group module, which uses "bulk part" of api, but I will make a separate feature pull request for it. 

Is anyone working on contact groups? In our group we also plan to integrate contact group management in ansible, API is quite similar to host groups, and one can directly  adapt this two modules then.

Best regards,
Michael

2022-09-22 12:03 UTC, robin-tribe29 commented
Hi Michael, thanks for your contribution! :clap: 
Let me answer the question about contact groups: To our knowledge, no one is working on that feature, so would appreciate it, if you contributed something there too. :partying_face:

2022-09-22 13:07 UTC, msekania commented
Hi @lgetwan,

test is included. I have also included parts for simple idem-potency tests for "present" and "absent".

Best regards,
Michael

2022-09-23 15:18 UTC, lgetwan requested changes
The module itself looks fine. Please try out the integration test using:
`ansible-test integration --docker default host_group`

2022-09-23 15:18 UTC, lgetwan commented on tests/integration/targets/host_group/tasks/test.yml
> +    folder: "{{ item.title }}"
Same here

2022-09-23 15:18 UTC, lgetwan commented on tests/integration/targets/host_group/tasks/test.yml
> +    folder: "{{ item.title }}"
and here

2022-09-23 15:18 UTC, lgetwan commented on tests/integration/targets/host_group/vars/main.yml
> +  - name:  "test1.tld"
"." is not a valid character in a host group name.

2022-09-23 15:18 UTC, lgetwan commented on tests/integration/targets/host_group/tasks/test.yml
> +  host:
should be host_group

2022-09-23 15:18 UTC, lgetwan commented on tests/integration/targets/host_group/tasks/test.yml
> +    folder: "{{ item.title }}"
host_group_name & title

2022-09-23 15:22 UTC, msekania commented on tests/integration/targets/host_group/tasks/test.yml
> +    folder: "{{ item.title }}"
I'll fix the file

2022-09-23 15:56 UTC, msekania commented
thanks! I had to be more careful :) 
I have made the changes.

2022-09-23 15:58 UTC, msekania reviewed
Thanks!
Corresponding changes have been made.

2022-09-23 15:58 UTC, msekania commented on tests/integration/targets/host_group/tasks/test.yml
> +    folder: "{{ item.title }}"
should be host_group_name & title

2022-09-23 15:58 UTC, msekania commented on tests/integration/targets/host_group/tasks/test.yml
> +    folder: "{{ item.title }}"
should be host_group_name & title

2022-09-23 15:58 UTC, msekania commented on tests/integration/targets/host_group/vars/main.yml
> +  - name:  "test1.tld"
Yes

2022-09-26 04:38 UTC, lgetwan requested changes
Hi Michael,
there are still two remains from the host module in your integration test playbook. Once they are removed, it runs like a charm.
Best regards
Lars

2022-09-26 04:38 UTC, lgetwan commented on tests/integration/targets/host_group/tasks/test.yml
> +      ipaddress: 127.0.0.1
These lines are only valid with the host or folder module.

2022-09-26 04:38 UTC, lgetwan commented on tests/integration/targets/host_group/tasks/test.yml
> +      ipaddress: 127.0.0.1
Same here.

2022-09-26 08:27 UTC, msekania commented on tests/integration/targets/host_group/tasks/test.yml
> +      ipaddress: 127.0.0.1
removed

2022-09-26 08:28 UTC, msekania commented on tests/integration/targets/host_group/tasks/test.yml
> +      ipaddress: 127.0.0.1
removed

2022-09-26 09:24 UTC, robin-tribe29 commented
Hi Micheal,

we are targeting #141 for the upcoming release, so I will merge this PR for the 0.12.0 release, pending a quick review of my own.
Thanks a lot for your contribution and your patience, we do appreciate it!

2022-09-26 12:11 UTC, robin-tribe29 commented
I just realized, that you put the module file in the root of the project, rather than `plugins/modules` @msekania, please fix that.

2022-09-26 16:36 UTC, msekania commented
@robin-tribe29 bulk host groups is now integrated in host_group module. tests are also extended.

2022-09-28 04:36 UTC, lgetwan approved these changes
Hi Michael,

looks very good from my point of view!
Thanks a lot for your work! :-)

Best regards
Lars

2022-09-28 04:36 UTC, merged

2022-09-29 07:57 UTC, msekania commented
Hi Lars,

> looks very good from my point of view!
Thanks!

There is one minor issue which I have noticed during contact_group.py generation.
In host_group.py module, in the examples part, I have overlooked "hostgroups".
In lines 70, 86, and 110, "hostgroups" should be updated to "host_groups"

Thanks, and best regards
Michael

2022-10-10 12:58 UTC, robin-tribe29 commented
Fixed in 4d09a6cf38ada63ff49d99f29bbfa029b5fe1dd5.