Local download
tribe29/ansible-collection-tribe29.checkmk pull request #183
Opened 2022-10-27 10:03 UTC by tonk

In our site only the Ansible Control node is allowed to contact the Checkmk server on port 443. So the download of the agent
and the API calls need to go through the Ansible control node. 

I have added an `checkmk_agent_delegate_download` option to delegate the download.

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [x] Other (please describe):
   For Red Hat and Suse based systems the agent was installed multiple times. Removed this duplicate code.

## What is the current behavior?

It is now possible to let the Ansible Control node download the Checkmk agent and transfer it to the remote node.

## What is the new behavior?

- Download the Checkmk agent on the control and transfer it when needed

## Other information

2022-10-27 13:49 UTC, robin-tribe29 commented on roles/agent/README.md
> +Configure the host to which Checkmk API dowloads are delegated to. After download the files are transfered to the remote node.
You might want to clarify, that this only applies, if the remote node is not downloading on its own.

2022-10-27 13:53 UTC, robin-tribe29 commented on roles/agent/tasks/main.yml
> +- name: "Transfer Checkmk CRE client to remote node"
Please refer to the agent as "agent", not "client". That might be confusing and would be inconsistent.

2022-10-28 05:54 UTC, tonk commented
Thanks for the very quick response.
I totally agree with your suggestions and have changed the code and documentation accordingly.

2022-11-04 16:53 UTC, robin-tribe29 requested changes
Fix the typo and we are good to merge. :)

2022-11-04 16:53 UTC, robin-tribe29 commented on roles/agent/README.md
> +Configure the host to which Checkmk API dowloads are delegated to. After download the files are transfered to the remote node, when the remote node didn't do the download.
Minor typo: dowloads

2022-11-04 16:54 UTC, robin-tribe29 commented
The reason for the failing tests was fixed in #6b0fd6dae4d6972566a615fd30084088e85a5232, so I am going to merge this after the requested fix.

2022-11-08 07:17 UTC, tonk commented
I fixed the `dowload` typo. No problem to merge it later. I'm already very happy that it's accepted.

2022-11-08 07:34 UTC, merged