Feature agent windows support
tribe29/ansible-collection-tribe29.checkmk pull request #187
Opened 2022-11-01 11:15 UTC by muehlings

## Pull request type

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the new behavior?
This is my contribution to PR #156

- Changes in linux agent roles
- Addition in windows agent roles
- Preparation files for WinRM to work

2022-11-03 09:41 UTC, muehlings commented
Sorry, but I have no idea how to change the behavior of github concerning these checks:
1. Running sanity test "line-endings"
```
ERROR: Found 3 line-endings issue(s) which need to be resolved:
ERROR: preparation/ansible-winrm/00-ansible.cmd:0:0: use "\n" for line endings instead of "\r\n"
```
Line ending of \r\n is correct, because those are windows cmd files. I tried to set the line ending in .gitattributes to LF or CRLF but the check always fails.

2. Running sanity test "pslint"
```
ERROR: Found 6 pslint issue(s) which need to be resolved:
ERROR: preparation/ansible-winrm/ConfigureRemotingForAnsible.ps1:281:58: PSCustomUseLiteralPath: Use the explicit -LiteralPath parameter name instead of -Path
```
This script is from [ansible ](https://github.com/ansible/ansible/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1) and I don't want to change anything in it.

I would prefer to skip the tests on both types of files (.cmd and .ps1) at the moment.

2022-11-04 16:39 UTC, robin-tribe29 commented
I agree, that we can ignore those tests right now.
Let me review your changes and try to understand them, before we merge them.

2022-11-04 16:47 UTC, robin-tribe29 requested changes
Overall I see a lot of potential here, but I think we need to make sure we focus on the task at hand. I would like to keep the PR as small and simple as possible, before doing major reorganization of the role.

2022-11-04 16:47 UTC, robin-tribe29 commented on playbooks/example-linux-inventory.yml
> +---
Do we need this playbook, or is it for your local testing only? If the latter is true, please remove it from the PR.

2022-11-04 16:47 UTC, robin-tribe29 commented on playbooks/example-windows-inventory.yml
> +---
Do we need this playbook, or is it for your local testing only? If the latter is true, please remove it from the PR.

2022-11-04 16:47 UTC, robin-tribe29 commented on roles/agent/tasks/Debian.yml
> +- name: "({{ansible_os_family}}) Derivates: Download host-specific Checkmk {{ checkmk_agent_edition | upper }} Agent."
Why are you doing this? We are clearly in Debian.yml, so we can - and in my opinion should - hard code it in the task name. Unless you can convince me, why this makes sense, I would ask you to revert it. Especially to keep the PR as clean as possible.

2022-11-04 16:47 UTC, robin-tribe29 commented on roles/agent/tasks/Linux.yml
> +---
Is this new file structure necessary for your PR to work, or can we do changes one step at a time?

2022-11-04 16:47 UTC, robin-tribe29 commented on roles/agent/tasks/Win32NT.yml
> +---
Why this distinction with Win32NT? Is this related to the overall change in the file structure?

2022-11-07 07:27 UTC, muehlings commented on roles/agent/tasks/Debian.yml
> +- name: "({{ansible_os_family}}) Derivates: Download host-specific Checkmk {{ checkmk_agent_edition | upper }} Agent."
I had to move a lot of tasks from the new generic "ansible_system" (Win32NT/Linux) to the "ansible_os_family" and back to see, if they were running like expected and in the right context. The download agent part is for example identical on all linux derivates because it is an builtin ansible method. I left the names with the variables because it doesn't hurt to have it generalized across the includes.

2022-11-07 07:28 UTC, muehlings commented on roles/agent/tasks/Linux.yml
> +---
main.yml had to be split up because it was Linux-only. Linux.yml is the generic linux branch with ansible-related tasks and nothing derivate-specific.

2022-11-07 07:49 UTC, muehlings commented on roles/agent/tasks/Win32NT.yml
> +---
main.yml had to be split up because it was Linux-only. Win32NT.yml is the generic Windows branch with ansible-related tasks and nothing derivate-specific.

The role structure now looks like:
```
main
+-Linux (ansible_system)
|  +- Debian (ansible_os_family)
|  +- RedHat (ansible_os_family)
|  +- SuSE (ansible_os_family)
|  +- ...
+- Win32NT (ansible_system)
   +- Windows (ansible_os_family)
```

ansible_system contains the following tags/commands (mostly shell):
- get-package-facts
- download-package
- include-os-family-tasks
- cmk-update-agent
- cmk-agent-ctl

ansible_os_family contains the following tags/commands (mostly package manager):
- download-package (host specific)
- install-package (apt, yum, ..., win_package)
- configure_firewall

2022-11-07 07:51 UTC, muehlings commented on playbooks/example-linux-inventory.yml
> +---
They were for local testing. I deleted them.

2022-11-07 07:52 UTC, muehlings commented on playbooks/example-windows-inventory.yml
> +---
They were for local testing. I deleted them.

2022-11-30 15:19 UTC, merged