allow to specify the position of created rules
tribe29/ansible-collection-tribe29.checkmk pull request #208
Opened 2022-12-14 17:59 UTC by geof77

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ X ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

No way to specify the position of the rule in the rule folder, so it is always created at the bottom.

## What is the new behavior?

There is a new "position" parameter to specify the position of the rule.

## Other information

Tested with CheckMK 2.1p14

2022-12-15 06:27 UTC, robin-tribe29 commented
The integration tests are flaky, but please try to fix the findings of the other tests. If you need help, do let me know.

2022-12-16 06:46 UTC, robin-tribe29 commented
Hi @geof77 and thanks for the update. We are waiting for a review of your code before moving forward with the merge.
We will keep you posted here. Thanks again for your contribution!

2022-12-16 15:17 UTC, lgetwan requested changes
Great idea to make the rules position aware!
I haven't tested your code yet, I just read it, and I added some little ideas on how to further improve it and make it bulletproof.

Thanks for your work! :-)

2022-12-16 15:17 UTC, lgetwan commented on plugins/modules/rule.py
> +        "before_specific_rule",
Can you add code examples for "before_specific_rule" and "bottom_of folder", as well?

2022-12-16 15:17 UTC, lgetwan commented on plugins/modules/rule.py
> +        and (position.get("rule_id") is None or position.get("rule_id") == "")
The rule_id of the existing rule (for the "before_" or "after_") has to be provided in the ansible task, correct?
As far as I can see, there's no way to query the rule_id of an existing rule with our collection, yet.
Have you thought of returning the ID of a freshly created rule back to the ansible caller?

Having an Ansible lookup plugin for that, one day, would be great, too. :-)

2022-12-16 15:17 UTC, lgetwan commented on plugins/modules/rule.py
> +    rule_id = json.loads(response.read().decode("utf-8"))["id"]
What if the response cannot be decoded or "id" is not found in the resulting dict?

2022-12-16 15:49 UTC, geof77 commented on plugins/modules/rule.py
> +        and (position.get("rule_id") is None or position.get("rule_id") == "")
Yes I already have code for returning the rule_id so in can be reused in subsequent tasks.  But I'm wondering if it would be useful to return the whole response from the API instead of the ID only. Maybe there are useful values other than the ID in there...

2022-12-16 15:55 UTC, geof77 commented on plugins/modules/rule.py
> +    rule_id = json.loads(response.read().decode("utf-8"))["id"]
I assumed the HTTP status would be different from 200 and this part of the code would never be reached. But, ok, let's make this better.

2022-12-19 10:33 UTC, lgetwan commented on plugins/modules/rule.py
> +        and (position.get("rule_id") is None or position.get("rule_id") == "")
That's correct. Hopefully, I'll have a bit of time for that in Q1 next year. If you're faster than that and you have a good idea how to solve that, go for it. :-D

2022-12-19 17:53 UTC, geof77 commented on plugins/modules/rule.py
> +        and (position.get("rule_id") is None or position.get("rule_id") == "")
Now returns the response from the API.

2022-12-19 17:53 UTC, geof77 commented on plugins/modules/rule.py
> +        "before_specific_rule",
Done.

2022-12-19 17:58 UTC, geof77 commented on plugins/modules/rule.py
> +    rule_id = json.loads(response.read().decode("utf-8"))["id"]
I had a look at the other modules in the collection, none of them check for decode exceptions, so the module would just fail and we would see the cause in the ansible debug output...

2022-12-19 22:50 UTC, msekania commented on plugins/modules/rule.py
> +        and (position.get("rule_id") is None or position.get("rule_id") == "")
Just a small question, @geof77 @lgetwan,

would not it be more appropriate to use  "bottom_of_ruleset" and "top_of_ruleset" instead of  "bottom_of_folder", and "top_of_folder", since these terms address positions within the ruleset?

2022-12-20 09:30 UTC, geof77 commented on plugins/modules/rule.py
> +        and (position.get("rule_id") is None or position.get("rule_id") == "")
Sure, however these are the keywords used by the API. I don't like this, but that's the way it is....

2022-12-20 12:45 UTC, geof77 commented on plugins/modules/rule.py
> +        and (position.get("rule_id") is None or position.get("rule_id") == "")
What about simply having "top", "bottom", "before" and "after". That would be easier.
Also, having to write "position" twice is not pretty.

`    position: {"position":"top_of_folder"}`

So I would rather have something like:

```
    move:
       positiion: "top"
```

Or 

```
    move:
      position: "after"
      rule_id: "123456789abcdef"
```

Is that better?

2022-12-22 00:27 UTC, geof77 commented on plugins/modules/rule.py
> +        and (position.get("rule_id") is None or position.get("rule_id") == "")
To better understand what "move" does, this is what I came up with:

```
    move:
        description:
          - Move the rule at the specified location
          - Mutually exclusive with state: absent
        type: dict
        suboptions:
            position:
                description: Position of the rule in the folder
                required: true
                type: str
                choices:
                    - "top"
                    - "bottom"
                    - "before"
                    - "after"
            rule_id:
                description:
                    - Move the rule "before" or "after" this rule_id
                    - Required with position: "before" or "after"
                    - Mutually exclusive with position: "top" or "bottom"
                type: str
            folder:
                description:
                    - Folder the rule should be moved to
                    - Required with position: "top" or "bottom"
                    - Mutually exclusive with position: "before" and "after"
                default: "/"
```

I already have this in my fork but still polishing the code.

2022-12-22 10:40 UTC, robin-tribe29 commented on plugins/modules/rule.py
> +        and (position.get("rule_id") is None or position.get("rule_id") == "")
From a non-developer perspective this looks great to me!
Looking forward to the finalized version.

2022-12-24 11:37 UTC, geof77 commented
Now we have:
* the new "move" param
* the API response returned so we can get the rule id out of it

To keep this PR simple, the move param only works with rule creation for now. Next I'd like to introduce a new "rule_id" parameter. With this new parameter we will be able to use rule IDs to move or delete existing rules. I left some examples in the EXAMPLES section.

2023-01-03 14:28 UTC, geof77 commented
It's been a few days now and before going further I'd like your advice on a few design questions:
* Do you prefer the module returns only the rule id or the entire response from the API?  Do you think there is anything useful in the response other than the ID?
*  The response from the API is currently stored in a dict named "content" because this is what the uri module uses. But it might be better/prettier to call it something else, maybe "response" ? OK with "content"?
* Next I will add the rule_id param so we can move or delete existing rules by providing their rule id like in the examples I have left in the code (search for "TODO"). What do you think of this? Do I proceed here or should I make another PR for this?
Comments/suggestions are welcome...

2023-01-03 17:09 UTC, geof77 commented
Well I finally managed to get ansible-test running on my setup. Hopefully this passes the tests now. Sorry for the errors.

2023-01-04 08:16 UTC, robin-tribe29 commented
@geof77 no need to apologize, we do definitely appreciate your work! :pray:

I am no developer though, and we are always short on resources, so please bear with us until someone can answer your questions and review the code properly.

2023-01-04 14:14 UTC, geof77 commented
@lgetwan : Indeed I don't see anything useful other than the ID in the response. So I'm going to make the change and just call it "id". That's straightforward and prettier :) We can always add a field with the full content in the future, if we ever need it.

2023-01-11 10:30 UTC, robin-tribe29 commented on plugins/modules/rule.py
> +                    - Mutually exclusive with I(position=before) and I(after).
I for my part do agree with @lgetwan. :upside_down_face:

2023-01-12 16:05 UTC, geof77 commented on plugins/modules/rule.py
> +                    - Mutually exclusive with I(position=before) and I(after).
Ok for me to rename it "location". 

I wonder if "location" should be a suboption of the "rule" param rather than a top-level option. Maybe it could be used instead of the existing "folder" suboption (which is redundant and would be deprecated). Currently, "folder" cannot be specified under 'location' and the folder is simply copied from the other "folder" option.

I.E.:

```
rule:
  location:
     folder: "/tst" 
     position: "top"
```
looks better than
```
rule:
  folder: "/tst"
location:
   position: "top"
```

Here's what I also have in the queue for now :

* better parameter checking, moved to run_module instead of inside the move_rule function
* do not return a diffrent message if the rule is moved
* documentation correction for the errors you spotted and some others
* ability to use a rule_id instead of a full rule description
* Idempotency is a bit tricky. Currently, when the rule is already created and the task is re-run, the location will not change, so if we create a rule at the top of a fodler, than a bunch of others on top of that, we might not want the first rule to be moved to the top again. So maybe introduce a 'force_move' option...
* moving existing rules
* checking if the rule has moved so we return the correct status ("ok" vs. "changed")
* ...

2023-01-13 12:04 UTC, lgetwan commented on plugins/modules/rule.py
> +                    - Mutually exclusive with I(position=before) and I(after).
This looks indeed better, I agree:

```
rule:
  location:
     folder: "/tst" 
     position: "top"
```
Regarding your to-do queue: Please only include _those_ of them into this PR, that are necessary to have a working version. Then, we can have this released, and people can use it. :-)
The rest of your queue can then result in (a) new PR(s).

Thanks again for your contribution!

2023-01-15 11:19 UTC, geof77 commented
To be clear, what this PR does for end users is:
* return the ID of the rule when it is created or when it already exists so it can be used in subsequent tasks
* add a new "location" sub-option to the "rule" parameter for precise positioning of created rules
* deprecate the "folder" sub-option in favor of the new "location" sub-option

Internally, this means:
* a new get_rule_etag function to get the etag header required when moving a rule
* a new move_rule function to move the rule at the specified location, called after the rule is created
* modification of the create_rule function so it returns the ID of the created rule
* modification of the exit_* functions to make the rule ID available in ansible tasks
* arguments validation and default settings for the rule option and the location sub-option
* documentation of the rule option and its location sub-option
* examples using the new location option

2023-01-17 05:57 UTC, lgetwan commented
That sounds excellent!
Today, I will do some testing and then, most likely, merge your PR.

2023-01-17 11:39 UTC, geof77 commented
@lgetwan : great! I have just added the deprecation warning if forgot to include so users are warned.

2023-01-17 12:51 UTC, lgetwan approved these changes
I did some tests, and they were all successful. :-) 
Your PR makes the rule module even better.
Thanks for your contribution!

2023-01-17 12:57 UTC, merged