[host module] also manage cluster hosts
tribe29/ansible-collection-tribe29.checkmk pull request #246
Opened 2023-01-29 14:35 UTC by elwood218

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

So far there only "normal" hosts can be added.

Issue Number: `e.g. #1`

## What is the new behavior?

- Create cluster hosts
- Update nodes of cluster host

## Other information

I have commented out a part in the code of changing a host to a cluster and vice versa. Maybe that function shall be used too? But for now it is a deleting of the host an re-create. Can that be done in another way?

2023-01-30 07:41 UTC, robin-tribe29 commented
Hi @elwood218 and thank you for your contribution, it is very much appreciated! :pray: 
Can we get the tests nice and green? Then we will review your changes and prepare for merging, if there are no problems.
We are in a brief freeze of merging, but will continue within a week.

2023-02-10 12:58 UTC, lgetwan requested changes
Good idea to add that functionality!
I already successfully tested your modifications.
There's only one comment and one small change request below.

2023-02-10 12:58 UTC, lgetwan commented on plugins/modules/host.py
> +    )
Wouldn't it be better to return "cluster" as current_state instead of returning two separate variables?

2023-02-10 19:21 UTC, elwood218 commented on plugins/modules/host.py
> +    )
Don't know exactly what you mean. Do you mean "cluster.nodes" and "cluster.is_cluster" ?

2023-02-13 05:43 UTC, lgetwan commented on plugins/modules/host.py
> +    )
No, I meant: In case of a cluster, you could return "cluster" in the variable "current_state" instead of introducing a new variable "current_cluster".

2023-02-22 10:24 UTC, lgetwan commented on plugins/modules/host.py
> +    )
Hi @elwood218, 
as soon as you have removed the (IMHO) unneeded variable "current_cluster" from line 220, we can merge the PR into the devel branch.
Can you please check?

2023-05-02 03:38 UTC, closed without merging

2023-12-21 09:36 UTC, meni2029 commented
Hello @elwood218, it seems it was very close, why did you give up on this good contribution ?