add module for adding passwords
tribe29/ansible-collection-tribe29.checkmk pull request #247
Opened 2023-01-29 15:30 UTC by elwood218

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Passwords cannot be added.

## What is the new behavior?

- Passwords can be added or deleted to/out of the password store.
- If passwords exists nothing will be done.

## Other information

If I would knew how to read passwords if I am logged in on the Checkmk server then it would be possible to compare passwords and change them. For now it only would be possible to create a password and could think about to force password set to overwrite it nevertheless if it differs or not.
The API lets only set "editable by" to a contact group the editor is part of. So as user "automation" I can only set "admin" if automation would be Administrator.

2023-02-10 13:18 UTC, lgetwan requested changes
I successfully tested your new module. Thanks for contributing!

I like Your idea to provide a "force new password". What do you think about doing it like this:

- present: creates a pw, if absent and doesn't do anything if the pw is already present.
- absent: deletes a pw if existing
- reset: resets the "password" value if the pw exists. If the pw doesn't exist, it exits with "failed"

2023-02-10 19:04 UTC, elwood218 commented
@lgetwan Hi. What do you mean by "reset"? For me reset more sounds like setting a changed password back to the previous. 
Btw is there a way to read password on cli?

2023-02-13 05:37 UTC, lgetwan commented
@elwood218: There might be better words than "reset", true.
I guess, there _is_ a way to decrypt the PW store on the CLI. I haven't tried, yet. Maybe, having a close look at ~/lib/check_mk/utils/password_store.py and encryption.py helps.Also checkout https://checkmk.com/werk/13633

2023-02-13 17:17 UTC, elwood218 commented
@lgetwan Yes I already had a look into both you mentioned. Thought or hoped there is a CLI command for that. But then first let us implement like how it is now and later think of the other way.

2023-02-21 15:22 UTC, robin-tribe29 reviewed
Is there a reason, that you do not deal with the "shared" key from the API?

2023-02-21 15:22 UTC, robin-tribe29 commented on plugins/modules/password.py
> +    ident:
In the `tag_group` module we use "id". I think we should do that here too.
I am aware, that the API calls it "ident", but I think "id" is better understood.

2023-02-21 15:22 UTC, robin-tribe29 commented on plugins/modules/password.py
> +"""
I think in both examples the "password" key is missing, right?

2023-02-22 07:47 UTC, lgetwan commented
Ok, my wording "reset password" was probably a bad choice. What I meant:

1. state = "absent": Delete password entry if existing.
2. state = "present": Create password entry if not existing. If existing, do NOT touch the actual password, even if the parameter is set.
3. state = "reset": Create password entry if not existing. If existing, set the actual password to the value of the password parameter.

What wording would you suggest instead of "reset"? "overwrite" or "force_new_password" might be alternatives, but I think, I'm not on the peak of my creativity, today. :-p

2023-02-22 10:26 UTC, elwood218 commented
@lgetwan I would say "force" or "overwrite" because "force" for example is also used in other similar Ansible modules if I remember correct.

2023-02-23 07:23 UTC, robin-tribe29 commented
Is there a perceivable use case, where you want to use "present" to ensure a password is there without changing anything? I feel like the answer here is "no". So I would expect, that "present" ensures the password I want to set is actually set, without caring about a potentially existing password.

I feel like "reset" is still more confusing, although I get your idea @lgetwan. But I also feel like "force" should not be necessary. If there is a use case for my former example, then I think we should go with "present", "absent" and "force".

P.S.: @elwood218 you marked my comments as resolved, but I see no new commits, nor a comment from you. Do you just need to push the changes?

2023-05-03 03:38 UTC, closed without merging