Feature rule check mode
tribe29/ansible-collection-tribe29.checkmk pull request #258
Opened 2023-02-03 18:06 UTC by geof77

Check mode support for rules module.

In check mode, the module will only return what modifications it would do, without actually making any modificiation.

Suggestions welcome.

## Pull request type

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?
No check mode

Issue Number: #181

## What is the new behavior?

Alow ansible's --check parameter.

2023-02-10 06:03 UTC, lgetwan requested changes
Great idea to enable the check mode! Thanks!
I just found one case (when move_rule() is involved) where it fails in check mode.

2023-02-10 06:03 UTC, lgetwan commented on plugins/modules/rule.py
> +    if module.check_mode:
When doing a "create rule on top of ruleset", the move_rule() gets a "None" for the rule_id and fails when setting the api_endpoint.
Also, the "get_rule_etag()" fails in that case, because of the invalid rule_id.

2023-02-10 08:58 UTC, geof77 commented on plugins/modules/rule.py
> +    if module.check_mode:
I reverted my last commit, that should fix these.

2023-02-10 09:39 UTC, geof77 commented
Just added a message that we are in check mode, like this:
```
TASK [cmkserver : Test rule from collection] ***************************
changed: [ilx00073] => {"changed": true, "id": null, "msg": "Rule created (check_mode: no changes made)"}
```

2023-02-14 06:04 UTC, lgetwan approved these changes

2023-02-21 12:50 UTC, merged