Extend rule module integration tests
tribe29/ansible-collection-tribe29.checkmk pull request #291
Opened 2023-03-26 08:31 UTC by godspeed-you

The code to contact the Checkmk API is redundantly placed all over the modules. This projects aims to centralize this code into a single library to make our lifes more easy. Later changes may be done in one single place instead of changing several dozens of code lines.

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe):

## What is the current behavior?

- Currently, if the API headers or other static information is changed, this needs to be adapted in an unclear amount of files and code lines. 
- Everytime a new API call to Checkmk is added, bugs or slightly different behaviour may be introduced.

## What is the new behavior?

- The centralized file may be called by every module to have a defined set of functionality returned information.
- This set may be used to derive a module specific class to address specific requirements.
- The result of this API call is stored in a defined and clearly structured data set. This allows to automatically provide a clear and reliable set of information after the API call.

## Other information

This PR contains a migrated module as an example on how to use this new library. The changes have been reduced to an absolute minimum to minimize potential bugs. So potential further refactorings may be skipped to have this change less complex.

2023-03-27 11:54 UTC, lgetwan reviewed
I really like the way you unified and simplified the API calls!
I have a question regarding the definition of the inheriting class, though. In some modules, there are multiple, different POST or GET calls. How would you define the related 
`def post(self)`
calls for those?

2023-03-27 13:53 UTC, msekania commented
related #176

2023-03-27 14:34 UTC, msekania commented
@godspeed-you,

First of all thanks,

Concerning module, in essence it should at least cover all already implemented usage in different modules, otherwise it will be yet another modules which one has to adjust manually per module and not the central one.

2023-03-28 04:30 UTC, lgetwan commented
I agree to update the modules one by one. And I agree, it's probably easier to have separate feature branches for each module change.
Thanks for updating the user module, as well!

2023-03-28 07:41 UTC, msekania commented
@godspeed-you,

when structure is fixed and accepted, I will also help with group modules.

2023-03-28 08:52 UTC, robin-tribe29 requested changes

2023-03-28 08:52 UTC, robin-tribe29 commented on plugins/modules/activation.py
> +version_added: "0.0.2"
Why did you change this? This reflects the version of the collection the module was introduced to. There is no independent versioning of modules.

2023-03-29 08:35 UTC, godspeed-you commented on plugins/modules/activation.py
> +version_added: "0.0.2"
My bad. I overlooked the name of the variable and only read the comment. This is resolved by the last commit.

2023-03-29 11:27 UTC, lgetwan approved these changes
Looks fine!

2023-03-29 11:37 UTC, robin-tribe29 approved these changes

2023-03-29 11:37 UTC, merged