Add task to update site
tribe29/ansible-collection-tribe29.checkmk pull request #88
Opened 2022-07-29 08:25 UTC by diademiemi

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

This PR adds a task to update a site to a given version of Checkmk. 

It uses a small bash if statement to check if the version given is higher than the currently used version, then it uses the omd update command to update the site.
I'm using the force flag since otherwise it would create an interactive dialogue and hang.

The task will not run unless a method for conflict resolution is given in the `update_conflict_resolution` variable of the site

2022-07-29 08:27 UTC, diademiemi commented
I've tested it to upgrade between different versions in 2.1. I made the conflict resolution a required variable instead of setting a default so that it would force you to read the documentation on updating servers before using this

2022-07-29 16:23 UTC, robin-tribe29 commented
Hi @diademiemi! We already discussed this feature internally and the result of that discussion was, that we want to stay careful here. The reason is, that this feature might suggest, that updating can be done without further user attention, which is not true in the end.
Let me raise this topic with our product management again and see where we can get.

2022-08-04 06:14 UTC, diademiemi commented
I see. I believe this is a safe way to do since it requires giving a variable out of a few choices for it to not skip the task, so you would have to read the documentation and know the risks

2022-08-09 11:42 UTC, diademiemi commented
Gonna work on implementing these changes right now

2022-08-09 12:37 UTC, diademiemi commented
Doing all the logic through Ansible now instead of a bash if statement, much cleaner this way, took a while to get right though.

If the site version differs from what is given in the variables. it imports a new tasks file `update-site.yml` which checks if the required variables are given and if the new version is installed.

After that it does a 5 second pause for patch updates with a notice. For major updates, it does 60 seconds.

It then creates a backup of the site and updates the site.

2022-08-10 06:40 UTC, robin-tribe29 requested changes

2022-08-10 06:40 UTC, robin-tribe29 commented on roles/server/tasks/update-site.yml
> +      omd backup {{ item.item.name }} {{ checkmk_server_backup_dir }}/{{ item.item.name }}-backup-$(date +%Y%m%d-%H%M%S).zip
We should do this default backup without history and graphs. This is just for disaster recovery. Users should have proper backups in advance.

2022-08-10 06:40 UTC, robin-tribe29 commented on roles/server/defaults/main.yml
> +checkmk_server_backup_dir: /opt/omd/sites/
I do not like the path, I would rather go with `/tmp/`.
I know it might be small in size, but the backup should be too (see comment in `update-site.yml`).
That way the backup will be cleaned up upon reboot, and we do not need to worry about automated backups filling up disk space.
I am open for suggestions though.

2022-08-10 06:40 UTC, robin-tribe29 commented on roles/server/tasks/update-site.yml
> +      omd backup {{ item.item.name }} {{ checkmk_server_backup_dir }}/{{ item.item.name }}-backup-$(date +%Y%m%d-%H%M%S).zip
Another option would be to carve the backup job out completely and make it fully configurable in its own file.
Then we could include it here with the settings mentioned above.

2022-08-10 09:34 UTC, diademiemi commented on roles/server/tasks/update-site.yml
> +      omd backup {{ item.item.name }} {{ checkmk_server_backup_dir }}/{{ item.item.name }}-backup-$(date +%Y%m%d-%H%M%S).zip
That sounds good yeah. What files should be backed up then?

2022-08-10 09:35 UTC, diademiemi commented on roles/server/defaults/main.yml
> +checkmk_server_backup_dir: /opt/omd/sites/
Knowing the files will b smaller I think this is preferable too. I didn't go for /tmp at first since with the size of these files that wouldn't even work in my test environment. But if the files are smaller, I think that's fine

2022-08-10 10:05 UTC, robin-tribe29 commented on roles/server/tasks/update-site.yml
> +      omd backup {{ item.item.name }} {{ checkmk_server_backup_dir }}/{{ item.item.name }}-backup-$(date +%Y%m%d-%H%M%S).zip
From the help:
```
Possible options for this command:
 --no-rrds            do not copy RRD files (performance data)
 --no-logs            do not copy the monitoring history and log files
 -N,--no-past         do not copy RRD files, the monitoring history and log files
 --no-compression      do not compress tar archive
```
I would go with `--no-past`.

2022-08-10 10:06 UTC, diademiemi commented on roles/server/tasks/update-site.yml
> +      omd backup {{ item.item.name }} {{ checkmk_server_backup_dir }}/{{ item.item.name }}-backup-$(date +%Y%m%d-%H%M%S).zip
I see, I'll add that. Also didn't realise it was a tar file and not a zip, I'll change the filename too

2022-08-11 14:22 UTC, robin-tribe29 requested changes

2022-08-11 14:22 UTC, robin-tribe29 commented on roles/server/README.md
> +        update_conflict_resolution: install
We should include this variable in `defaults/main.yml` but set it to an empty value. That way we are consistent, while still avoiding undesired updates.
Also, the variable should abide by the naming scheme (checkmk_server_foo).

2022-08-11 14:22 UTC, robin-tribe29 commented on roles/server/defaults/main.yml
> +checkmk_server_backup_opts: '--no-past'
We are missing a newline at the end of the file. :upside_down_face:

2022-08-11 14:22 UTC, robin-tribe29 commented on roles/server/tasks/update-site.yml
> +  when: item.item.update_conflict_resolution is undefined
This check fails for me, even if I set the variable. I also do not fully understand, what the `item.item` does here.

2022-08-11 14:22 UTC, robin-tribe29 commented on roles/server/tasks/update-site.yml
> +---
Try to run `ansible-lint` and `yamllint` against your changes, there will be some findings.
Our CI will do this at a later stage too, and at some point, we will also run this checks against PRs.

2022-08-11 14:25 UTC, diademiemi commented on roles/server/tasks/update-site.yml
> +---
Yes will fix and will do from now on

2022-08-11 14:30 UTC, diademiemi commented on roles/server/tasks/update-site.yml
> +  when: item.item.update_conflict_resolution is undefined
`update_conflict_resolution` is a variable I have set per site. like this:

```yaml
checkmk_server_sites:
  - name: site
    version: "2.1.0p9"
    state: started
    admin_pw: testing
    update_conflict_resolution: install
```
If you'd prefer it to just be a variable like `checkmk_server_update_conflict_resolution` in the root of the variables I can adjust it to that.


The `item.item` is an artifact of how looping over multiple items is done with `include_tasks`. The root of the `item` contains the results of the comparison of the versions in the task from `sites.yml`, the `item.item` includes the variable it used for it, which in this case is the site definition in the variables. I don't believe there's a better way to loop through a list of tasks per item.. I wish `block:` had that functionality, for now doing an `include_tasks` is seemingly the best way to do it.

2022-08-11 15:35 UTC, robin-tribe29 commented on roles/server/tasks/update-site.yml
> +  when: item.item.update_conflict_resolution is undefined
Well, that my moment of dumbness for this week. :facepalm: 
Forget I said anything, your implementation makes perfect sense.

2022-08-11 16:24 UTC, diademiemi commented on roles/server/defaults/main.yml
> +checkmk_server_backup_opts: '--no-past'
Fixed!

2022-08-11 16:27 UTC, diademiemi commented on roles/server/README.md
> +        update_conflict_resolution: install
You said in the other comment that this implementation is good, so should this stay like this? I don't think having this as a default is possible since it's part of a list.

Also, I changed the example from install to abort, I feel like that's safer to have in a README since people will interpret it as a "default".

2022-08-12 10:30 UTC, robin-tribe29 commented on roles/server/README.md
> +        update_conflict_resolution: install
Yeah, as said in the other comment, I don't know where my mind was.
What you did makes perfect sense.

I like the new default. :+1:

2022-08-12 11:41 UTC, robin-tribe29 commented on roles/server/tasks/update-site.yml
> +  when: item.item.version | regex_replace('p.*', '') != item.stdout | regex_replace('p.*', '')
We need to think about downgrades here. While not being officially supported, they are often conducted.
I have no opinion yet, just want to leave a note, so we do not forget.

2022-08-12 11:45 UTC, diademiemi commented on roles/server/tasks/update-site.yml
> +  when: item.item.version | regex_replace('p.*', '') != item.stdout | regex_replace('p.*', '')
I don't think the playbook prevents a downgrade like this. I could add a task to compare the values and check if it's an upgrade or downgrade (Though parsing this might be a bit difficult but I think Ansible has some lookups you can use for version strings like these). Then have a boolean that defaults to false on whether to allow downgrades.

2022-08-12 11:48 UTC, robin-tribe29 commented on roles/server/tasks/update-site.yml
> +  when: item.item.version | regex_replace('p.*', '') != item.stdout | regex_replace('p.*', '')
That sounds like a sound approach. :+1:

2022-08-12 11:49 UTC, robin-tribe29 commented
No idea, why the sanity checks suddenly fail, but the error is not related to the changes in here.

2022-08-12 11:50 UTC, diademiemi commented
Yes I see, looks good!

2022-08-12 11:50 UTC, diademiemi commented on roles/server/tasks/update-site.yml
> +  when: item.item.version | regex_replace('p.*', '') != item.stdout | regex_replace('p.*', '')
Alright I'll work on that in a little bit

2022-08-12 12:10 UTC, lgetwan commented
Automatic updating is a risky step, but it looks like @diademiemi has built in some safety features that reduce this risk. :-)
I'll give it a go!

2022-08-16 18:11 UTC, diademiemi commented on roles/server/tasks/update-site.yml
> +  when: item.item.version | regex_replace('p.*', '') != item.stdout | regex_replace('p.*', '')
My bad this took so long, other things got in the way. Just pushed a commit that adds a boolean `checkmk_server_allow_downgrades` that defaults to false. If this is set to false there's a task that uses Ansibles `version` test to compare the versions.

2022-08-22 06:46 UTC, diademiemi commented
Any updates on this? @robin-tribe29, did you see comment on the downgrade check, does this resolve it in your opinion?
I tested some cases by comparing some fake versions with varying amounts of decimals to make sure it doesn't error (for example detect `p21` as a downgrade to `p3`) and it seems like Ansible parses this correctly.

2022-08-23 06:23 UTC, robin-tribe29 commented
Sorry for the delay @diademiemi! I was meaning to merge and release this, but I was on a business trip and this week starts loaded with appointments. But I will get back to this within the week, pinky promise! :)

2022-08-23 06:27 UTC, diademiemi commented
I see, no worries!

2022-08-24 12:41 UTC, robin-tribe29 commented on roles/server/README.md
> +Whether to allow downgrading a sites version.
We should note here, that this creates an unsupported setup for enterprise customers I think.

2022-08-24 12:41 UTC, robin-tribe29 commented on roles/server/README.md
> +    checkmk_server_backup_dir: /opt/omd/sites
I think this is out of sync with `defaults/main.yml` right?

2022-08-24 12:41 UTC, robin-tribe29 commented on roles/server/tasks/update-site.yml
> +  when: item.item.version | regex_replace('p.*', '') != item.stdout | regex_replace('p.*', '')
Looks great!
I am testing this right now.

2022-08-24 12:42 UTC, diademiemi commented on roles/server/README.md
> +    checkmk_server_backup_dir: /opt/omd/sites
Yes correct, I'll edit this

2022-08-24 12:42 UTC, diademiemi commented on roles/server/README.md
> +Whether to allow downgrading a sites version.
I'll add a note for this!

2022-08-24 12:54 UTC, robin-tribe29 commented on roles/server/tasks/update-site.yml
> +  when: item.item.version | regex_replace('p.*', '') != item.stdout | regex_replace('p.*', '')
When testing this with versions 2.1.0p9 and 2.1.0p1, the downgrade check does not seem to work.
I might be doing something here though.

2022-08-24 12:57 UTC, diademiemi commented on roles/server/tasks/update-site.yml
> +  when: item.item.version | regex_replace('p.*', '') != item.stdout | regex_replace('p.*', '')
I'll have a look and see what's up

2022-08-24 13:06 UTC, diademiemi commented on roles/server/tasks/update-site.yml
> +  when: item.item.version | regex_replace('p.*', '') != item.stdout | regex_replace('p.*', '')
Looks to be caused by the variable in the defaults being `'false`', which when not casted to a boolean will equal true. Will push a commit to fix this

2022-08-24 13:07 UTC, diademiemi commented on roles/server/tasks/update-site.yml
> +  when: item.item.version | regex_replace('p.*', '') != item.stdout | regex_replace('p.*', '')
I must've been testing in my vars with just `true` and `false`

2022-08-24 13:31 UTC, robin-tribe29 commented
I just realized, that we might run into merge conflicts, or overwrite some stuff, as the firewalls task in this branch was fixed in another PR. Do you know a good way how to tackle this @diademiemi?

2022-08-24 13:34 UTC, diademiemi commented
Once the change requests are accepted GitHub should show if merging can be done automatically or if manual intervention is required. If manual intervention is required it'll open an editor when you attempt to merge which shows conflicts. It'll then show proposalsand you can choose between them or manually insert your own. It's likely it'll have a proposal which is what the devel branch has right now (The fixed version) and you can just click on that.

2022-08-24 13:35 UTC, diademiemi commented
Actually it says in the sub test merging can be performed automatically. So I think it should be fine (Which makes sense, as the modified files in that PR were not modified in this PR, and the defaults.yml is very easy for Git to automatically correct)

2022-08-24 13:39 UTC, robin-tribe29 approved these changes

2022-08-24 13:40 UTC, merged